<template>
  <v-btn
    fab
    fixed
    bottom
    right
    color="secondary"
    @click="$vuetify.goTo(0)"
    target="_blank"
    rel="noopener"
  >
    <v-icon>mdi-chevron-up</v-icon>
  </v-btn>
</template>
